In [2]:
nx=64
ny=64

In [9]:
(1e-7*torch.rand(ny,nx) + 1e-6*(torch.ones((ny,1)) * torch.rand(1,nx) ))

torch.Size([64, 64])

In [12]:
torch.stack((torch.zeros(nx,nx),torch.zeros(nx,nx)))

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [1]:
import torch
import numpy as np

In [2]:
torch.rand(2,2)

tensor([[0.8505, 0.9775],
        [0.1650, 0.6387]])

In [3]:
class QG_kernel():
    def __init__(
        self,
        nx=64
        L=1e6,                      # domain size is L [m]
        beta=1.5e-11,               # gradient of coriolis parameter
        rek=5.787e-7,               # linear drag in lower layer
        rd=15000.0,                 # deformation radius
        delta=0.25,                 # layer thickness ratio (H1/H2)
        H1 = 500,                   # depth of layer 1 (H1)
        U1=0.025,                   # upper layer flow
        U2=0.0,                     # lower layer flow
        **kwargs
        ):
        """
        Parameters
        ----------

        beta : number
            Gradient of coriolis parameter. Units: meters :sup:`-1`
            seconds :sup:`-1`
        rek : number
            Linear drag in lower layer. Units: seconds :sup:`-1`
        rd : number
            Deformation radius. Units: meters.
        delta : number
            Layer thickness ratio (H1/H2)
        U1 : number
            Upper layer flow. Units: meters seconds :sup:`-1`
        U2 : number
            Lower layer flow. Units: meters seconds :sup:`-1`
        """

        # physical
        self.beta = beta
        #self.rek = rek
        self.rd = rd
        self.delta = delta
        self.Hi = np.array([ H1, H1/delta])
        self.U1 = U1
        self.U2 = U2
        self.nx = nx
        self.ny = nx


        # initial conditions: (PV anomalies)
        self.set_q1q2()
        
    def set_q1q2(self):
        self.q=torch.stack((1e-7*torch.rand(self.ny,self.nx) + 1e-6*(torch.ones((self.ny,1)) * torch.rand(1,self.nx) ),torch.zeros(self.nx,self.nx)))
        
    def timestep(self):
        """ Advance system forward in time one step """
        
        """ 1. Need a function for the RHS
            2. Pass RHS to some numerical solver
            
        """
        
    def rhs(self):
        """ Essentially build a tensor of dq/dt """
        

In [4]:
qg_kernel=QG_kernel()

In [5]:
qg_kernel.q

tensor([[[2.0993e-07, 3.6425e-07, 6.0980e-07,  ..., 1.0314e-06,
          5.6419e-07, 6.0985e-07],
         [1.5738e-07, 2.8919e-07, 6.0423e-07,  ..., 9.4039e-07,
          5.2460e-07, 5.4372e-07],
         [1.9607e-07, 3.5660e-07, 6.7206e-07,  ..., 9.3997e-07,
          5.6840e-07, 5.9360e-07],
         ...,
         [1.8000e-07, 3.2151e-07, 6.1705e-07,  ..., 9.9809e-07,
          5.3923e-07, 6.1448e-07],
         [1.5192e-07, 3.8386e-07, 6.6572e-07,  ..., 1.0193e-06,
          5.4849e-07, 5.7937e-07],
         [1.7754e-07, 3.4494e-07, 6.1240e-07,  ..., 9.5277e-07,
          5.4559e-07, 5.4892e-07]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.000

In [6]:
### Get streamfunction?
### d2/dx2 psi = q + psi

In [7]:
q=qg_kernel.q[0]
psi=torch.zeros(q.shape)

In [8]:
qh=np.fft.fft(q+psi)
#psih=np.fft.fft(psi)

In [9]:
np.fft.ifft(-qh/())

ValueError: operands could not be broadcast together with shapes (64,64) (0,) 